apiVersion: v1
kind: Service
metadata:
  name: protected-service-api
  namespace: k8s-logs
  labels:
    app: protected-service
spec:
  type: ClusterIP
  selector:
    name: protected-service-api
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
