apiVersion: apps/v1
kind: Deployment
metadata:
  name: protected-service-api
  namespace: k8s-logs
  labels:
    app: protected-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protected-service
      name: protected-service-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: protected-service
        name: protected-service-api
    spec:
      containers:
        - args:
            - yarn
            - start
          env:
            - name: USER_HEADER_NAME
              valueFrom:
                configMapKeyRef:
                  name: protected-service-api-env
                  key: USER_HEADER_NAME
            - name: SERVICE_EXCHANGE_HEADER_NAME
              valueFrom:
                configMapKeyRef:
                  name: protected-service-api-env
                  key: SERVICE_EXCHANGE_HEADER_NAME
            - name: SERVICE_EXCHANGE_KEY
              valueFrom:
                configMapKeyRef:
                  name: protected-service-api-env
                  key: SERVICE_EXCHANGE_KEY
          name: protected-service-backend
          image: us-central1-docker.pkg.dev/k8s-logs-387417/k8s-logs-repo/protected-service-api:latest
#          image: protected_service/backend
#          imagePullPolicy: Never
          ports:
            - containerPort: 3000
      restartPolicy: Always
