services:
  db:
    image: postgres:15.2-alpine
    environment:
      - POSTGRES_DB=k8s_logs_rest_api
      - POSTGRES_USER=rest_api
      - POSTGRES_PASSWORD=1234
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pg-data:
