apiVersion: v1
kind: Service
metadata:
  name: auth-service-api
  namespace: k8s-logs
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    name: auth-service-api
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8000
