apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-small-volume
  labels:
    type: local
spec:
  storageClassName: local-small
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  labels:
    app: auth-service
spec:
  storageClassName: local-small
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200M