apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-database
  namespace: k8s-logs
  labels:
    app: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      name: auth-service-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-service
        name: auth-service-database
    spec:
      containers:
        - image: postgres:15.2-alpine
          name: auth-service-database
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: auth-service-database-env
                  key: POSTGRES_DB
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: auth-service-database-env
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: auth-service-database-env
                  key: POSTGRES_USER
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      restartPolicy: Always
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: database-volume-claim
