apiVersion: v1
kind: Service
metadata:
  name: auth-service-database
  namespace: k8s-logs
  labels:
    app: auth-service
spec:
  type: ClusterIP
  selector:
    name: auth-service-database
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
