apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-small-volume
  namespace: k8s-logs
  labels:
    type: local
spec:
  storageClassName: local-small
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /var/lib/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-volume-claim
  namespace: k8s-logs
  labels:
    app: auth-service
spec:
  storageClassName: local-small
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200M