apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-api
  namespace: k8s-logs
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      name: gateway-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gateway
        name: gateway-api
    spec:
      containers:
        - args:
            - kong
            - start
            - -c
            - kong.conf
          name: gateway-api
          image: us-central1-docker.pkg.dev/k8s-logs-387417/k8s-logs-repo/gateway-api:latest
          ports:
            - containerPort: 8000
      restartPolicy: Always
