apiVersion: v1
kind: Service
metadata:
  name: gateway-api
  labels:
    app: gateway
spec:
  type: LoadBalancer
  selector:
    name: gateway-api
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
    - name: "8001"
      port: 8001
      targetPort: 8001
