apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-api
  namespace: k8s-logs
  labels:
    app: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
      name: auth-service-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth-service
        name: auth-service-api
    spec:
      containers:
        - args:
            - uvicorn
            - main:app
            - --reload
            - --host
            - 0.0.0.0
            - --port
            - "8000"
            - --log-config
            - logging_config.conf
          env:
            - name: DATABASE_URL
              value: {{ .Values.authService.env.DATABASE_URL }}
            - name: SERVICE_EXCHANGE_HEADER_NAME
              value: {{ .Values.authService.env.SERVICE_EXCHANGE_HEADER_NAME }}
            - name: SERVICE_EXCHANGE_KEY
              value: {{ .Values.authService.env.SERVICE_EXCHANGE_KEY }}
          name: auth-service-backend
          image: {{ .Values.authService.image}}
          imagePullPolicy: {{ .Values.imagePolicy}}
          ports:
            - containerPort: 8000
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-api
  namespace: k8s-logs
  labels:
    app: auth-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    name: auth-service-api
  ports:
    - name: "8083"
      port: 8083
      targetPort: 8000
