import os

API_PREFIX = '/api'
DATABASE_URL = os.getenv('DATABASE_URL')
SERVICE_EXHANGE_HEADER_NAME = os.getenv('SERVICE_EXHANGE_HEADER_NAME', '')
SERVICE_EXHANGE_KEY = os.getenv('SERVICE_EXHANGE_KEY', '')
